# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 576688cf381956c9f3cb2ff9e1ba4351d198513478e85f53004657a7e81b61724a6b5af3e1b7d6ce9e3dc91d6e1c278b0de5fa1c31627c556cb026319270c051

test:
  secret_key_base: 8e4bd7fe01b39aa29c29fb81879932febd0603712308e714ffdd624a366df473abb5643cab7a69b3d035bc87ecdc45cecf81816d1073f732c8d958ded9d5bedb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
